
- name: setup 
  hosts: all 
  remote_user: "{{user}}"
  become: yes
  roles:
    - setup

- name: setup-shell 
  hosts: all 
  remote_user: "{{user}}"
  roles:
    - setup-shell
  tags: shell 

# - name: setup-amazonlinux2 
#   hosts: all 
#   remote_user: "{{user}}"
#   become: yes
#   roles:
#     - setup-amazonlinux2
#   tags: amazonlinux2 


