version: '3.7'
services:
  mariadb:
    build: ./mariadb
    restart: always
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker_data/db/data:/var/lib/mysql

    # ./にする必要？

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./src:/var/www/html
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      # PMA_USER: root
      # PMA_PASSWORD: mandala
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mariadb
    volumes:
     - "./docker_data/phpmyadmin/sessions:/sessions"
# volumes:
#   wordpress:
#   mariadb:
