
- name: set swap on centos 
  shell: |
    dd if=/dev/zero of=/swapfile bs=1M "count={{swap_size}}"
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
  become: yes
