---
# This playbook contains common plays that will be run on all nodes.
- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

# /etc/resolv.confにこれ追加しておく docker上でのdns解決
# # Google nameservers
# nameserver 8.8.8.8
# nameserver 8.8.4.4

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install dev package
  yum: 
    name:
      - tmux
      # - neovim
      - git
      - mariadb
      - go

- name: install docker 
  shell: |
    amazon-linux-extras install docker -y
    usermod -a -G docker "{{user}}" 
    amazon-linux-extras install epel -y
    curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose`

- name: Make sure a docker is running
  systemd:
    state: started 
    enabled: yes
    name: docker 

