
- name: Install common dependencies
  dnf: 
    name:
     - docker
     - docker-compose 
  become: yes

- name: Create a phpmyadmin container
  community.general.docker_container:
    name: phpmyadmin 
    image: phpmyadmin/phpmyadmin:latest 
    restart_policy: always
    ports:
      - "9000:80"
    env:
      PMA_HOST: "{{pma_host}}"
    volumes:
      - ./docker_data/phpmyadmin/sessions:/sessions 

