---
# This playbook contains common plays that will be run on all nodes.
- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

# /etc/resolv.confにこれ追加しておく docker上でのdns解決
# # Google nameservers
# nameserver 8.8.8.8
# nameserver 8.8.4.4

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install common dependencies
  yum: 
    name:
     - epel-release  #amazon linux 2ではみつからない
     - libselinux-python
     - libsemanage-python
     - setools-console #seinfoコマンド
     - python-setuptools
     - zsh
     - tmux
     - git
     - lsof
     - cmake
     - wget
     - yum-utils
    #  - neovim
    #  - htop
    state: present

    #    - snapd

   #  sudo systemctl enable --now snapd.socket
   # sudo ln -s /var/lib/snapd/snap /snap

- name: install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

- name: install dev package
  yum: 
    name:
      - bzip2-devel
      - gdbm-devel
      - libffi-devel
      - libuuid-devel
      - ncurses-devel
      - openssl-devel
      - readline-devel
      - sqlite-devel
      - tk-devel
      - xz-devel
      - zlib-devel
      - httpd-tools # basic 認証の時必要
    state: present


# Mecab
# - name: install dev package
#   yum: 
#     name: https://packages.groonga.org/centos/groonga-release-latest.noarch.rpm
#     state: present

# Mecab
# - name: mecab用でgroongaを入れる
#   yum:
#     name: 
#       - groonga
#     enablerepo: "epel"
#     state: present
# - name: install dev package
#   yum: 
#     name:
#       - mecab
#       - mecab-ipadic
# - name: install rust
#   shell: |
#     curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly


# - name: install docker
#   snap:
#     name: docker

